name: Visual Regression Tests

on:
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  visual-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run Visual Regression tests
        run: npx playwright test visual.spec.ts --project=chromium
        continue-on-error: true
        env:
          CI: true

      - name: Upload visual regression results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: visual-regression-report
          path: |
            playwright-report/
            test-results/
          retention-days: 30

      - name: Comment PR with visual differences
        if: github.event_name == 'pull_request' && failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⚠️ Visual regression tests detected differences. Please review the artifacts for details.'
            })
